import type { Metadata } from "next";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { AuthProvider } from "./context/AuthContext";
import { Poppins , Montserrat } from "next/font/google";

import "./globals.css";

export const montserrat = Montserrat({
  subsets: ['latin'],
  weight:'400',
  variable:'--font-montserrat'
})
export const PoppinFont = Poppins({
  subsets: ['latin'],
  weight:'400',
  variable:'--font-poppins'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html lang="en">
      <body
        className={`${montserrat.variable} ${PoppinFont.variable} antialiased mt-20`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
    </AuthProvider>
  );
}
